EZP-32107: Impl. visitor for Score sort clause
ezsystems/ezplatform-solr-search-engine pull request #203
Opened 2020-10-27 23:09 UTC by adamwojs

> JIRA: https://jira.ez.no/browse/EZP-32107

### Description

Impl. visitor for Score sort clause.

2020-10-28 11:52 UTC, alongosz requested changes
Naming

2020-10-28 11:52 UTC, alongosz commented on lib/Resources/config/container/solr/sort_clause_visitors.yml
> +        class: EzSystems\EzPlatformSolrSearchEngine\Query\Common\SortClauseVisitor\Score
Technical debt
```suggestion
    EzSystems\EzPlatformSolrSearchEngine\Query\Common\SortClauseVisitor\Score:
```

or:
```suggestion
    ibexa.platform.search.solr.query.common.sort_clause_visitor.score:
        class: EzSystems\EzPlatformSolrSearchEngine\Query\Common\SortClauseVisitor\Score
```

2020-10-29 20:28 UTC, adamwojs commented on lib/Resources/config/container/solr/sort_clause_visitors.yml
> +        class: EzSystems\EzPlatformSolrSearchEngine\Query\Common\SortClauseVisitor\Score
No, isn't technical dept. Nevertheless class name could be used as service id. See 922feaf

2020-10-30 06:37 UTC, Steveb-p approved these changes

2020-10-30 09:29 UTC, alongosz approved these changes

2020-11-04 09:29 UTC, mnocon approved these changes

2020-11-04 11:06 UTC, merged