IBX-1699: Bump requirement for Solr
ezsystems/ezplatform-solr-search-engine pull request #228
Opened 2022-01-06 16:26 UTC by glye

Install Solr 8.11.1 by default, as this includes the upgraded log4j with an important security fix.
For 2.0 branch, eZ Platform v2.5 (as of https://github.com/ezsystems/ezplatform/pull/677 )

Work in progress:
- [x] Install Solr 8.11.1
- [ ] Readme update is incomplete

2022-01-10 10:02 UTC, alongosz requested changes

2022-01-10 10:02 UTC, alongosz commented on .travis.yml
> +        - php: 7.2
7.1 is still supported for 2.5, so we need to run those tests on that PHP version.

2022-01-10 11:32 UTC, glye commented on .travis.yml
> +        - php: 7.2
Resolved in https://github.com/ezsystems/ezplatform-solr-search-engine/pull/228/commits/52739f00279a4558fbf23d20ddf9c2fc78e819d8

2022-01-10 11:38 UTC, alongosz requested changes

2022-01-10 11:38 UTC, alongosz commented on README.md
> +- v1.8+: eZ Platform 2.5LTS+ *(bundled out of the box)* with Solr 8.11.1
What do you mean by 1.8? I can't see such version.

2022-01-10 11:38 UTC, alongosz commented on bin/.travis/init_solr.sh
> +        7.7.* | 8.[5-8].* | 8.11.* )
How about simply:
```suggestion
        7.7.* | 8.[5-11].* )
```

2022-01-10 11:38 UTC, alongosz commented on bin/generate-solr-config.sh
> +cp ${SOLR_INSTALL_DIR}/server/solr/configsets/sample_techproducts_configs/conf/{currency.xml,elevate.xml} $DESTINATION_DIR
I'm not 100% sold on using sample configs in prod setup. Requires @adamwojs' opinion.

2022-01-10 11:50 UTC, mnocon commented on bin/generate-solr-config.sh
> +cp ${SOLR_INSTALL_DIR}/server/solr/configsets/sample_techproducts_configs/conf/{currency.xml,elevate.xml} $DESTINATION_DIR
Sorry, this is my fault - I tried my best to make CI pass in https://github.com/ezsystems/ezplatform-solr-search-engine/pull/226#issuecomment-999538777 and experimented with some things to see if they could work (it couldn't, because that branch did not support Solr 8)

This line should not be here, same for https://github.com/ezsystems/ezplatform-solr-search-engine/pull/228/files#diff-6f8576ce077c26ef5bce5d98d321d898e6da287700a5eecdf86f0abc96371976R230-R234

2022-01-10 11:51 UTC, mnocon commented on bin/.travis/init_solr.sh
> +    local config_dir_samples="${INSTALL_DIR}/server/solr/configsets/sample_techproducts_configs/conf"
Please see https://github.com/ezsystems/ezplatform-solr-search-engine/pull/228/files#r781117412

2022-01-10 12:13 UTC, glye commented on README.md
> +- v1.8+: eZ Platform 2.5LTS+ *(bundled out of the box)* with Solr 8.11.1
Meaning newer than 1.7. But agree it's better to say 2.0+. Fixed.

2022-01-10 12:14 UTC, glye commented
Review fixes: Readme, and removed sample configs.

2022-01-10 12:17 UTC, alongosz approved these changes
LGTM. Requires @adamwojs' review.

2022-01-10 14:47 UTC, glye commented
Reverted https://github.com/ezsystems/ezplatform-solr-search-engine/pull/228/commits/f14f88349c6170158403c81bfd1be929e275cbad as it breaks the build, probably a regexp actually, so it won't work like that.

2022-01-12 11:05 UTC, tomaszszopinski approved these changes
QA approved on eXPlatform 2.5 (with ezplatform-solr-search-engine 2.0).

2022-01-12 12:53 UTC, merged